#!/bin/bash
# scp files to OSU server for web demo

scp /Users/zhangyilin/0_pipi/LKB_OSU/Research/RNA/web_demo_canvas/demo_chart_style.css liukaib@flop.engr.oregonstate.edu:/nfs/stak/users/liukaib/public_html/
scp /Users/zhangyilin/0_pipi/LKB_OSU/Research/RNA/web_demo_canvas/demo_json+canvas.html liukaib@flop.engr.oregonstate.edu:/nfs/stak/users/liukaib/public_html/
scp /Users/zhangyilin/0_pipi/LKB_OSU/Research/RNA/web_demo_canvas/demo_myScript.js liukaib@flop.engr.oregonstate.edu:/nfs/stak/users/liukaib/public_html/
scp /Users/zhangyilin/0_pipi/LKB_OSU/Research/RNA/web_demo_canvas/trial_dataOnServer.js liukaib@flop.engr.oregonstate.edu:/nfs/stak/users/liukaib/public_html/
scp /Users/zhangyilin/0_pipi/LKB_OSU/Research/RNA/web_demo_canvas/trial_dataOnServer.html liukaib@flop.engr.oregonstate.edu:/nfs/stak/users/liukaib/public_html/
